// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rerac/protos/instance_collection.proto

package rerac.protos;

public final class InstanceCollection {
  private InstanceCollection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FeatureMapOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string feature = 1;
    java.util.List<String> getFeatureList();
    int getFeatureCount();
    String getFeature(int index);
    
    // repeated int32 featureHash = 2;
    java.util.List<java.lang.Integer> getFeatureHashList();
    int getFeatureHashCount();
    int getFeatureHash(int index);
    
    // repeated string category = 3;
    java.util.List<String> getCategoryList();
    int getCategoryCount();
    String getCategory(int index);
  }
  public static final class FeatureMap extends
      com.google.protobuf.GeneratedMessage
      implements FeatureMapOrBuilder {
    // Use FeatureMap.newBuilder() to construct.
    private FeatureMap(Builder builder) {
      super(builder);
    }
    private FeatureMap(boolean noInit) {}
    
    private static final FeatureMap defaultInstance;
    public static FeatureMap getDefaultInstance() {
      return defaultInstance;
    }
    
    public FeatureMap getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rerac.protos.InstanceCollection.internal_static_rerac_protos_FeatureMap_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rerac.protos.InstanceCollection.internal_static_rerac_protos_FeatureMap_fieldAccessorTable;
    }
    
    // repeated string feature = 1;
    public static final int FEATURE_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList feature_;
    public java.util.List<String>
        getFeatureList() {
      return feature_;
    }
    public int getFeatureCount() {
      return feature_.size();
    }
    public String getFeature(int index) {
      return feature_.get(index);
    }
    
    // repeated int32 featureHash = 2;
    public static final int FEATUREHASH_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> featureHash_;
    public java.util.List<java.lang.Integer>
        getFeatureHashList() {
      return featureHash_;
    }
    public int getFeatureHashCount() {
      return featureHash_.size();
    }
    public int getFeatureHash(int index) {
      return featureHash_.get(index);
    }
    
    // repeated string category = 3;
    public static final int CATEGORY_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList category_;
    public java.util.List<String>
        getCategoryList() {
      return category_;
    }
    public int getCategoryCount() {
      return category_.size();
    }
    public String getCategory(int index) {
      return category_.get(index);
    }
    
    private void initFields() {
      feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      featureHash_ = java.util.Collections.emptyList();;
      category_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < feature_.size(); i++) {
        output.writeBytes(1, feature_.getByteString(i));
      }
      for (int i = 0; i < featureHash_.size(); i++) {
        output.writeInt32(2, featureHash_.get(i));
      }
      for (int i = 0; i < category_.size(); i++) {
        output.writeBytes(3, category_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < feature_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(feature_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFeatureList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < featureHash_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(featureHash_.get(i));
        }
        size += dataSize;
        size += 1 * getFeatureHashList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < category_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(category_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCategoryList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rerac.protos.InstanceCollection.FeatureMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rerac.protos.InstanceCollection.FeatureMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rerac.protos.InstanceCollection.FeatureMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rerac.protos.InstanceCollection.FeatureMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rerac.protos.InstanceCollection.FeatureMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rerac.protos.InstanceCollection.FeatureMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rerac.protos.InstanceCollection.FeatureMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rerac.protos.InstanceCollection.FeatureMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rerac.protos.InstanceCollection.FeatureMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rerac.protos.InstanceCollection.FeatureMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rerac.protos.InstanceCollection.FeatureMap prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rerac.protos.InstanceCollection.FeatureMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rerac.protos.InstanceCollection.internal_static_rerac_protos_FeatureMap_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rerac.protos.InstanceCollection.internal_static_rerac_protos_FeatureMap_fieldAccessorTable;
      }
      
      // Construct using rerac.protos.InstanceCollection.FeatureMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        featureHash_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        category_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rerac.protos.InstanceCollection.FeatureMap.getDescriptor();
      }
      
      public rerac.protos.InstanceCollection.FeatureMap getDefaultInstanceForType() {
        return rerac.protos.InstanceCollection.FeatureMap.getDefaultInstance();
      }
      
      public rerac.protos.InstanceCollection.FeatureMap build() {
        rerac.protos.InstanceCollection.FeatureMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rerac.protos.InstanceCollection.FeatureMap buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rerac.protos.InstanceCollection.FeatureMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rerac.protos.InstanceCollection.FeatureMap buildPartial() {
        rerac.protos.InstanceCollection.FeatureMap result = new rerac.protos.InstanceCollection.FeatureMap(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          feature_ = new com.google.protobuf.UnmodifiableLazyStringList(
              feature_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.feature_ = feature_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          featureHash_ = java.util.Collections.unmodifiableList(featureHash_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.featureHash_ = featureHash_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          category_ = new com.google.protobuf.UnmodifiableLazyStringList(
              category_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.category_ = category_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rerac.protos.InstanceCollection.FeatureMap) {
          return mergeFrom((rerac.protos.InstanceCollection.FeatureMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rerac.protos.InstanceCollection.FeatureMap other) {
        if (other == rerac.protos.InstanceCollection.FeatureMap.getDefaultInstance()) return this;
        if (!other.feature_.isEmpty()) {
          if (feature_.isEmpty()) {
            feature_ = other.feature_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFeatureIsMutable();
            feature_.addAll(other.feature_);
          }
          onChanged();
        }
        if (!other.featureHash_.isEmpty()) {
          if (featureHash_.isEmpty()) {
            featureHash_ = other.featureHash_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFeatureHashIsMutable();
            featureHash_.addAll(other.featureHash_);
          }
          onChanged();
        }
        if (!other.category_.isEmpty()) {
          if (category_.isEmpty()) {
            category_ = other.category_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCategoryIsMutable();
            category_.addAll(other.category_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureFeatureIsMutable();
              feature_.add(input.readBytes());
              break;
            }
            case 16: {
              ensureFeatureHashIsMutable();
              featureHash_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addFeatureHash(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              ensureCategoryIsMutable();
              category_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string feature = 1;
      private com.google.protobuf.LazyStringList feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFeatureIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          feature_ = new com.google.protobuf.LazyStringArrayList(feature_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getFeatureList() {
        return java.util.Collections.unmodifiableList(feature_);
      }
      public int getFeatureCount() {
        return feature_.size();
      }
      public String getFeature(int index) {
        return feature_.get(index);
      }
      public Builder setFeature(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFeatureIsMutable();
        feature_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addFeature(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFeatureIsMutable();
        feature_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllFeature(
          java.lang.Iterable<String> values) {
        ensureFeatureIsMutable();
        super.addAll(values, feature_);
        onChanged();
        return this;
      }
      public Builder clearFeature() {
        feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addFeature(com.google.protobuf.ByteString value) {
        ensureFeatureIsMutable();
        feature_.add(value);
        onChanged();
      }
      
      // repeated int32 featureHash = 2;
      private java.util.List<java.lang.Integer> featureHash_ = java.util.Collections.emptyList();;
      private void ensureFeatureHashIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          featureHash_ = new java.util.ArrayList<java.lang.Integer>(featureHash_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<java.lang.Integer>
          getFeatureHashList() {
        return java.util.Collections.unmodifiableList(featureHash_);
      }
      public int getFeatureHashCount() {
        return featureHash_.size();
      }
      public int getFeatureHash(int index) {
        return featureHash_.get(index);
      }
      public Builder setFeatureHash(
          int index, int value) {
        ensureFeatureHashIsMutable();
        featureHash_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addFeatureHash(int value) {
        ensureFeatureHashIsMutable();
        featureHash_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllFeatureHash(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureFeatureHashIsMutable();
        super.addAll(values, featureHash_);
        onChanged();
        return this;
      }
      public Builder clearFeatureHash() {
        featureHash_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      
      // repeated string category = 3;
      private com.google.protobuf.LazyStringList category_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCategoryIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          category_ = new com.google.protobuf.LazyStringArrayList(category_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<String>
          getCategoryList() {
        return java.util.Collections.unmodifiableList(category_);
      }
      public int getCategoryCount() {
        return category_.size();
      }
      public String getCategory(int index) {
        return category_.get(index);
      }
      public Builder setCategory(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoryIsMutable();
        category_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addCategory(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoryIsMutable();
        category_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllCategory(
          java.lang.Iterable<String> values) {
        ensureCategoryIsMutable();
        super.addAll(values, category_);
        onChanged();
        return this;
      }
      public Builder clearCategory() {
        category_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      void addCategory(com.google.protobuf.ByteString value) {
        ensureCategoryIsMutable();
        category_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:rerac.protos.FeatureMap)
    }
    
    static {
      defaultInstance = new FeatureMap(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rerac.protos.FeatureMap)
  }
  
  public interface InstanceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .rerac.protos.Instance.Feature feature = 1;
    java.util.List<rerac.protos.InstanceCollection.Instance.Feature> 
        getFeatureList();
    rerac.protos.InstanceCollection.Instance.Feature getFeature(int index);
    int getFeatureCount();
    java.util.List<? extends rerac.protos.InstanceCollection.Instance.FeatureOrBuilder> 
        getFeatureOrBuilderList();
    rerac.protos.InstanceCollection.Instance.FeatureOrBuilder getFeatureOrBuilder(
        int index);
    
    // optional int32 category_index = 2 [default = 0];
    boolean hasCategoryIndex();
    int getCategoryIndex();
    
    // optional string category = 3;
    boolean hasCategory();
    String getCategory();
    
    // optional bool positive = 4 [default = true];
    boolean hasPositive();
    boolean getPositive();
  }
  public static final class Instance extends
      com.google.protobuf.GeneratedMessage
      implements InstanceOrBuilder {
    // Use Instance.newBuilder() to construct.
    private Instance(Builder builder) {
      super(builder);
    }
    private Instance(boolean noInit) {}
    
    private static final Instance defaultInstance;
    public static Instance getDefaultInstance() {
      return defaultInstance;
    }
    
    public Instance getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rerac.protos.InstanceCollection.internal_static_rerac_protos_Instance_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rerac.protos.InstanceCollection.internal_static_rerac_protos_Instance_fieldAccessorTable;
    }
    
    public interface FeatureOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int32 index = 1;
      boolean hasIndex();
      int getIndex();
      
      // required double value = 2;
      boolean hasValue();
      double getValue();
    }
    public static final class Feature extends
        com.google.protobuf.GeneratedMessage
        implements FeatureOrBuilder {
      // Use Feature.newBuilder() to construct.
      private Feature(Builder builder) {
        super(builder);
      }
      private Feature(boolean noInit) {}
      
      private static final Feature defaultInstance;
      public static Feature getDefaultInstance() {
        return defaultInstance;
      }
      
      public Feature getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rerac.protos.InstanceCollection.internal_static_rerac_protos_Instance_Feature_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rerac.protos.InstanceCollection.internal_static_rerac_protos_Instance_Feature_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required int32 index = 1;
      public static final int INDEX_FIELD_NUMBER = 1;
      private int index_;
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getIndex() {
        return index_;
      }
      
      // required double value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private double value_;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getValue() {
        return value_;
      }
      
      private void initFields() {
        index_ = 0;
        value_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasIndex()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, index_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, value_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, index_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, value_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      @java.lang.Override
      protected Object writeReplace() throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static rerac.protos.InstanceCollection.Instance.Feature parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static rerac.protos.InstanceCollection.Instance.Feature parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static rerac.protos.InstanceCollection.Instance.Feature parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static rerac.protos.InstanceCollection.Instance.Feature parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static rerac.protos.InstanceCollection.Instance.Feature parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static rerac.protos.InstanceCollection.Instance.Feature parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static rerac.protos.InstanceCollection.Instance.Feature parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static rerac.protos.InstanceCollection.Instance.Feature parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static rerac.protos.InstanceCollection.Instance.Feature parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static rerac.protos.InstanceCollection.Instance.Feature parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(rerac.protos.InstanceCollection.Instance.Feature prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements rerac.protos.InstanceCollection.Instance.FeatureOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return rerac.protos.InstanceCollection.internal_static_rerac_protos_Instance_Feature_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return rerac.protos.InstanceCollection.internal_static_rerac_protos_Instance_Feature_fieldAccessorTable;
        }
        
        // Construct using rerac.protos.InstanceCollection.Instance.Feature.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          index_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return rerac.protos.InstanceCollection.Instance.Feature.getDescriptor();
        }
        
        public rerac.protos.InstanceCollection.Instance.Feature getDefaultInstanceForType() {
          return rerac.protos.InstanceCollection.Instance.Feature.getDefaultInstance();
        }
        
        public rerac.protos.InstanceCollection.Instance.Feature build() {
          rerac.protos.InstanceCollection.Instance.Feature result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private rerac.protos.InstanceCollection.Instance.Feature buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          rerac.protos.InstanceCollection.Instance.Feature result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public rerac.protos.InstanceCollection.Instance.Feature buildPartial() {
          rerac.protos.InstanceCollection.Instance.Feature result = new rerac.protos.InstanceCollection.Instance.Feature(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.index_ = index_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof rerac.protos.InstanceCollection.Instance.Feature) {
            return mergeFrom((rerac.protos.InstanceCollection.Instance.Feature)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(rerac.protos.InstanceCollection.Instance.Feature other) {
          if (other == rerac.protos.InstanceCollection.Instance.Feature.getDefaultInstance()) return this;
          if (other.hasIndex()) {
            setIndex(other.getIndex());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasIndex()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                index_ = input.readInt32();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                value_ = input.readDouble();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required int32 index = 1;
        private int index_ ;
        public boolean hasIndex() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getIndex() {
          return index_;
        }
        public Builder setIndex(int value) {
          bitField0_ |= 0x00000001;
          index_ = value;
          onChanged();
          return this;
        }
        public Builder clearIndex() {
          bitField0_ = (bitField0_ & ~0x00000001);
          index_ = 0;
          onChanged();
          return this;
        }
        
        // required double value = 2;
        private double value_ ;
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public double getValue() {
          return value_;
        }
        public Builder setValue(double value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = 0D;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:rerac.protos.Instance.Feature)
      }
      
      static {
        defaultInstance = new Feature(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:rerac.protos.Instance.Feature)
    }
    
    private int bitField0_;
    // repeated .rerac.protos.Instance.Feature feature = 1;
    public static final int FEATURE_FIELD_NUMBER = 1;
    private java.util.List<rerac.protos.InstanceCollection.Instance.Feature> feature_;
    public java.util.List<rerac.protos.InstanceCollection.Instance.Feature> getFeatureList() {
      return feature_;
    }
    public java.util.List<? extends rerac.protos.InstanceCollection.Instance.FeatureOrBuilder> 
        getFeatureOrBuilderList() {
      return feature_;
    }
    public int getFeatureCount() {
      return feature_.size();
    }
    public rerac.protos.InstanceCollection.Instance.Feature getFeature(int index) {
      return feature_.get(index);
    }
    public rerac.protos.InstanceCollection.Instance.FeatureOrBuilder getFeatureOrBuilder(
        int index) {
      return feature_.get(index);
    }
    
    // optional int32 category_index = 2 [default = 0];
    public static final int CATEGORY_INDEX_FIELD_NUMBER = 2;
    private int categoryIndex_;
    public boolean hasCategoryIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCategoryIndex() {
      return categoryIndex_;
    }
    
    // optional string category = 3;
    public static final int CATEGORY_FIELD_NUMBER = 3;
    private Object category_;
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getCategory() {
      Object ref = category_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          category_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCategoryBytes() {
      Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool positive = 4 [default = true];
    public static final int POSITIVE_FIELD_NUMBER = 4;
    private boolean positive_;
    public boolean hasPositive() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getPositive() {
      return positive_;
    }
    
    private void initFields() {
      feature_ = java.util.Collections.emptyList();
      categoryIndex_ = 0;
      category_ = "";
      positive_ = true;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getFeatureCount(); i++) {
        if (!getFeature(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < feature_.size(); i++) {
        output.writeMessage(1, feature_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, categoryIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getCategoryBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(4, positive_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < feature_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, feature_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, categoryIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCategoryBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, positive_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rerac.protos.InstanceCollection.Instance parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rerac.protos.InstanceCollection.Instance parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rerac.protos.InstanceCollection.Instance parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rerac.protos.InstanceCollection.Instance parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rerac.protos.InstanceCollection.Instance parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rerac.protos.InstanceCollection.Instance parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rerac.protos.InstanceCollection.Instance parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rerac.protos.InstanceCollection.Instance parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rerac.protos.InstanceCollection.Instance parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rerac.protos.InstanceCollection.Instance parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rerac.protos.InstanceCollection.Instance prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rerac.protos.InstanceCollection.InstanceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rerac.protos.InstanceCollection.internal_static_rerac_protos_Instance_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rerac.protos.InstanceCollection.internal_static_rerac_protos_Instance_fieldAccessorTable;
      }
      
      // Construct using rerac.protos.InstanceCollection.Instance.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFeatureFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (featureBuilder_ == null) {
          feature_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          featureBuilder_.clear();
        }
        categoryIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        category_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        positive_ = true;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rerac.protos.InstanceCollection.Instance.getDescriptor();
      }
      
      public rerac.protos.InstanceCollection.Instance getDefaultInstanceForType() {
        return rerac.protos.InstanceCollection.Instance.getDefaultInstance();
      }
      
      public rerac.protos.InstanceCollection.Instance build() {
        rerac.protos.InstanceCollection.Instance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rerac.protos.InstanceCollection.Instance buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rerac.protos.InstanceCollection.Instance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rerac.protos.InstanceCollection.Instance buildPartial() {
        rerac.protos.InstanceCollection.Instance result = new rerac.protos.InstanceCollection.Instance(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (featureBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            feature_ = java.util.Collections.unmodifiableList(feature_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.feature_ = feature_;
        } else {
          result.feature_ = featureBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.categoryIndex_ = categoryIndex_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.category_ = category_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.positive_ = positive_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rerac.protos.InstanceCollection.Instance) {
          return mergeFrom((rerac.protos.InstanceCollection.Instance)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rerac.protos.InstanceCollection.Instance other) {
        if (other == rerac.protos.InstanceCollection.Instance.getDefaultInstance()) return this;
        if (featureBuilder_ == null) {
          if (!other.feature_.isEmpty()) {
            if (feature_.isEmpty()) {
              feature_ = other.feature_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFeatureIsMutable();
              feature_.addAll(other.feature_);
            }
            onChanged();
          }
        } else {
          if (!other.feature_.isEmpty()) {
            if (featureBuilder_.isEmpty()) {
              featureBuilder_.dispose();
              featureBuilder_ = null;
              feature_ = other.feature_;
              bitField0_ = (bitField0_ & ~0x00000001);
              featureBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFeatureFieldBuilder() : null;
            } else {
              featureBuilder_.addAllMessages(other.feature_);
            }
          }
        }
        if (other.hasCategoryIndex()) {
          setCategoryIndex(other.getCategoryIndex());
        }
        if (other.hasCategory()) {
          setCategory(other.getCategory());
        }
        if (other.hasPositive()) {
          setPositive(other.getPositive());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getFeatureCount(); i++) {
          if (!getFeature(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              rerac.protos.InstanceCollection.Instance.Feature.Builder subBuilder = rerac.protos.InstanceCollection.Instance.Feature.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFeature(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              categoryIndex_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              category_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              positive_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .rerac.protos.Instance.Feature feature = 1;
      private java.util.List<rerac.protos.InstanceCollection.Instance.Feature> feature_ =
        java.util.Collections.emptyList();
      private void ensureFeatureIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          feature_ = new java.util.ArrayList<rerac.protos.InstanceCollection.Instance.Feature>(feature_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          rerac.protos.InstanceCollection.Instance.Feature, rerac.protos.InstanceCollection.Instance.Feature.Builder, rerac.protos.InstanceCollection.Instance.FeatureOrBuilder> featureBuilder_;
      
      public java.util.List<rerac.protos.InstanceCollection.Instance.Feature> getFeatureList() {
        if (featureBuilder_ == null) {
          return java.util.Collections.unmodifiableList(feature_);
        } else {
          return featureBuilder_.getMessageList();
        }
      }
      public int getFeatureCount() {
        if (featureBuilder_ == null) {
          return feature_.size();
        } else {
          return featureBuilder_.getCount();
        }
      }
      public rerac.protos.InstanceCollection.Instance.Feature getFeature(int index) {
        if (featureBuilder_ == null) {
          return feature_.get(index);
        } else {
          return featureBuilder_.getMessage(index);
        }
      }
      public Builder setFeature(
          int index, rerac.protos.InstanceCollection.Instance.Feature value) {
        if (featureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeatureIsMutable();
          feature_.set(index, value);
          onChanged();
        } else {
          featureBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setFeature(
          int index, rerac.protos.InstanceCollection.Instance.Feature.Builder builderForValue) {
        if (featureBuilder_ == null) {
          ensureFeatureIsMutable();
          feature_.set(index, builderForValue.build());
          onChanged();
        } else {
          featureBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addFeature(rerac.protos.InstanceCollection.Instance.Feature value) {
        if (featureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeatureIsMutable();
          feature_.add(value);
          onChanged();
        } else {
          featureBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addFeature(
          int index, rerac.protos.InstanceCollection.Instance.Feature value) {
        if (featureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeatureIsMutable();
          feature_.add(index, value);
          onChanged();
        } else {
          featureBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addFeature(
          rerac.protos.InstanceCollection.Instance.Feature.Builder builderForValue) {
        if (featureBuilder_ == null) {
          ensureFeatureIsMutable();
          feature_.add(builderForValue.build());
          onChanged();
        } else {
          featureBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addFeature(
          int index, rerac.protos.InstanceCollection.Instance.Feature.Builder builderForValue) {
        if (featureBuilder_ == null) {
          ensureFeatureIsMutable();
          feature_.add(index, builderForValue.build());
          onChanged();
        } else {
          featureBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllFeature(
          java.lang.Iterable<? extends rerac.protos.InstanceCollection.Instance.Feature> values) {
        if (featureBuilder_ == null) {
          ensureFeatureIsMutable();
          super.addAll(values, feature_);
          onChanged();
        } else {
          featureBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearFeature() {
        if (featureBuilder_ == null) {
          feature_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          featureBuilder_.clear();
        }
        return this;
      }
      public Builder removeFeature(int index) {
        if (featureBuilder_ == null) {
          ensureFeatureIsMutable();
          feature_.remove(index);
          onChanged();
        } else {
          featureBuilder_.remove(index);
        }
        return this;
      }
      public rerac.protos.InstanceCollection.Instance.Feature.Builder getFeatureBuilder(
          int index) {
        return getFeatureFieldBuilder().getBuilder(index);
      }
      public rerac.protos.InstanceCollection.Instance.FeatureOrBuilder getFeatureOrBuilder(
          int index) {
        if (featureBuilder_ == null) {
          return feature_.get(index);  } else {
          return featureBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends rerac.protos.InstanceCollection.Instance.FeatureOrBuilder> 
           getFeatureOrBuilderList() {
        if (featureBuilder_ != null) {
          return featureBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(feature_);
        }
      }
      public rerac.protos.InstanceCollection.Instance.Feature.Builder addFeatureBuilder() {
        return getFeatureFieldBuilder().addBuilder(
            rerac.protos.InstanceCollection.Instance.Feature.getDefaultInstance());
      }
      public rerac.protos.InstanceCollection.Instance.Feature.Builder addFeatureBuilder(
          int index) {
        return getFeatureFieldBuilder().addBuilder(
            index, rerac.protos.InstanceCollection.Instance.Feature.getDefaultInstance());
      }
      public java.util.List<rerac.protos.InstanceCollection.Instance.Feature.Builder> 
           getFeatureBuilderList() {
        return getFeatureFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rerac.protos.InstanceCollection.Instance.Feature, rerac.protos.InstanceCollection.Instance.Feature.Builder, rerac.protos.InstanceCollection.Instance.FeatureOrBuilder> 
          getFeatureFieldBuilder() {
        if (featureBuilder_ == null) {
          featureBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rerac.protos.InstanceCollection.Instance.Feature, rerac.protos.InstanceCollection.Instance.Feature.Builder, rerac.protos.InstanceCollection.Instance.FeatureOrBuilder>(
                  feature_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          feature_ = null;
        }
        return featureBuilder_;
      }
      
      // optional int32 category_index = 2 [default = 0];
      private int categoryIndex_ ;
      public boolean hasCategoryIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCategoryIndex() {
        return categoryIndex_;
      }
      public Builder setCategoryIndex(int value) {
        bitField0_ |= 0x00000002;
        categoryIndex_ = value;
        onChanged();
        return this;
      }
      public Builder clearCategoryIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        categoryIndex_ = 0;
        onChanged();
        return this;
      }
      
      // optional string category = 3;
      private Object category_ = "";
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getCategory() {
        Object ref = category_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          category_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCategory(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        category_ = value;
        onChanged();
        return this;
      }
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000004);
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      void setCategory(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        category_ = value;
        onChanged();
      }
      
      // optional bool positive = 4 [default = true];
      private boolean positive_ = true;
      public boolean hasPositive() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getPositive() {
        return positive_;
      }
      public Builder setPositive(boolean value) {
        bitField0_ |= 0x00000008;
        positive_ = value;
        onChanged();
        return this;
      }
      public Builder clearPositive() {
        bitField0_ = (bitField0_ & ~0x00000008);
        positive_ = true;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rerac.protos.Instance)
    }
    
    static {
      defaultInstance = new Instance(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rerac.protos.Instance)
  }
  
  public interface InstanceCollectionPBOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .rerac.protos.FeatureMap map = 1;
    boolean hasMap();
    rerac.protos.InstanceCollection.FeatureMap getMap();
    rerac.protos.InstanceCollection.FeatureMapOrBuilder getMapOrBuilder();
    
    // repeated .rerac.protos.Instance instance = 2;
    java.util.List<rerac.protos.InstanceCollection.Instance> 
        getInstanceList();
    rerac.protos.InstanceCollection.Instance getInstance(int index);
    int getInstanceCount();
    java.util.List<? extends rerac.protos.InstanceCollection.InstanceOrBuilder> 
        getInstanceOrBuilderList();
    rerac.protos.InstanceCollection.InstanceOrBuilder getInstanceOrBuilder(
        int index);
  }
  public static final class InstanceCollectionPB extends
      com.google.protobuf.GeneratedMessage
      implements InstanceCollectionPBOrBuilder {
    // Use InstanceCollectionPB.newBuilder() to construct.
    private InstanceCollectionPB(Builder builder) {
      super(builder);
    }
    private InstanceCollectionPB(boolean noInit) {}
    
    private static final InstanceCollectionPB defaultInstance;
    public static InstanceCollectionPB getDefaultInstance() {
      return defaultInstance;
    }
    
    public InstanceCollectionPB getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rerac.protos.InstanceCollection.internal_static_rerac_protos_InstanceCollectionPB_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rerac.protos.InstanceCollection.internal_static_rerac_protos_InstanceCollectionPB_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .rerac.protos.FeatureMap map = 1;
    public static final int MAP_FIELD_NUMBER = 1;
    private rerac.protos.InstanceCollection.FeatureMap map_;
    public boolean hasMap() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public rerac.protos.InstanceCollection.FeatureMap getMap() {
      return map_;
    }
    public rerac.protos.InstanceCollection.FeatureMapOrBuilder getMapOrBuilder() {
      return map_;
    }
    
    // repeated .rerac.protos.Instance instance = 2;
    public static final int INSTANCE_FIELD_NUMBER = 2;
    private java.util.List<rerac.protos.InstanceCollection.Instance> instance_;
    public java.util.List<rerac.protos.InstanceCollection.Instance> getInstanceList() {
      return instance_;
    }
    public java.util.List<? extends rerac.protos.InstanceCollection.InstanceOrBuilder> 
        getInstanceOrBuilderList() {
      return instance_;
    }
    public int getInstanceCount() {
      return instance_.size();
    }
    public rerac.protos.InstanceCollection.Instance getInstance(int index) {
      return instance_.get(index);
    }
    public rerac.protos.InstanceCollection.InstanceOrBuilder getInstanceOrBuilder(
        int index) {
      return instance_.get(index);
    }
    
    private void initFields() {
      map_ = rerac.protos.InstanceCollection.FeatureMap.getDefaultInstance();
      instance_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMap()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getInstanceCount(); i++) {
        if (!getInstance(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, map_);
      }
      for (int i = 0; i < instance_.size(); i++) {
        output.writeMessage(2, instance_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, map_);
      }
      for (int i = 0; i < instance_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, instance_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rerac.protos.InstanceCollection.InstanceCollectionPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rerac.protos.InstanceCollection.InstanceCollectionPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rerac.protos.InstanceCollection.InstanceCollectionPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rerac.protos.InstanceCollection.InstanceCollectionPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rerac.protos.InstanceCollection.InstanceCollectionPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rerac.protos.InstanceCollection.InstanceCollectionPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rerac.protos.InstanceCollection.InstanceCollectionPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rerac.protos.InstanceCollection.InstanceCollectionPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rerac.protos.InstanceCollection.InstanceCollectionPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rerac.protos.InstanceCollection.InstanceCollectionPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rerac.protos.InstanceCollection.InstanceCollectionPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rerac.protos.InstanceCollection.InstanceCollectionPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rerac.protos.InstanceCollection.internal_static_rerac_protos_InstanceCollectionPB_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rerac.protos.InstanceCollection.internal_static_rerac_protos_InstanceCollectionPB_fieldAccessorTable;
      }
      
      // Construct using rerac.protos.InstanceCollection.InstanceCollectionPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMapFieldBuilder();
          getInstanceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (mapBuilder_ == null) {
          map_ = rerac.protos.InstanceCollection.FeatureMap.getDefaultInstance();
        } else {
          mapBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (instanceBuilder_ == null) {
          instance_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          instanceBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rerac.protos.InstanceCollection.InstanceCollectionPB.getDescriptor();
      }
      
      public rerac.protos.InstanceCollection.InstanceCollectionPB getDefaultInstanceForType() {
        return rerac.protos.InstanceCollection.InstanceCollectionPB.getDefaultInstance();
      }
      
      public rerac.protos.InstanceCollection.InstanceCollectionPB build() {
        rerac.protos.InstanceCollection.InstanceCollectionPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rerac.protos.InstanceCollection.InstanceCollectionPB buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rerac.protos.InstanceCollection.InstanceCollectionPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rerac.protos.InstanceCollection.InstanceCollectionPB buildPartial() {
        rerac.protos.InstanceCollection.InstanceCollectionPB result = new rerac.protos.InstanceCollection.InstanceCollectionPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (mapBuilder_ == null) {
          result.map_ = map_;
        } else {
          result.map_ = mapBuilder_.build();
        }
        if (instanceBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            instance_ = java.util.Collections.unmodifiableList(instance_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.instance_ = instance_;
        } else {
          result.instance_ = instanceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rerac.protos.InstanceCollection.InstanceCollectionPB) {
          return mergeFrom((rerac.protos.InstanceCollection.InstanceCollectionPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rerac.protos.InstanceCollection.InstanceCollectionPB other) {
        if (other == rerac.protos.InstanceCollection.InstanceCollectionPB.getDefaultInstance()) return this;
        if (other.hasMap()) {
          mergeMap(other.getMap());
        }
        if (instanceBuilder_ == null) {
          if (!other.instance_.isEmpty()) {
            if (instance_.isEmpty()) {
              instance_ = other.instance_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureInstanceIsMutable();
              instance_.addAll(other.instance_);
            }
            onChanged();
          }
        } else {
          if (!other.instance_.isEmpty()) {
            if (instanceBuilder_.isEmpty()) {
              instanceBuilder_.dispose();
              instanceBuilder_ = null;
              instance_ = other.instance_;
              bitField0_ = (bitField0_ & ~0x00000002);
              instanceBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInstanceFieldBuilder() : null;
            } else {
              instanceBuilder_.addAllMessages(other.instance_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMap()) {
          
          return false;
        }
        for (int i = 0; i < getInstanceCount(); i++) {
          if (!getInstance(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              rerac.protos.InstanceCollection.FeatureMap.Builder subBuilder = rerac.protos.InstanceCollection.FeatureMap.newBuilder();
              if (hasMap()) {
                subBuilder.mergeFrom(getMap());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMap(subBuilder.buildPartial());
              break;
            }
            case 18: {
              rerac.protos.InstanceCollection.Instance.Builder subBuilder = rerac.protos.InstanceCollection.Instance.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addInstance(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .rerac.protos.FeatureMap map = 1;
      private rerac.protos.InstanceCollection.FeatureMap map_ = rerac.protos.InstanceCollection.FeatureMap.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          rerac.protos.InstanceCollection.FeatureMap, rerac.protos.InstanceCollection.FeatureMap.Builder, rerac.protos.InstanceCollection.FeatureMapOrBuilder> mapBuilder_;
      public boolean hasMap() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public rerac.protos.InstanceCollection.FeatureMap getMap() {
        if (mapBuilder_ == null) {
          return map_;
        } else {
          return mapBuilder_.getMessage();
        }
      }
      public Builder setMap(rerac.protos.InstanceCollection.FeatureMap value) {
        if (mapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          map_ = value;
          onChanged();
        } else {
          mapBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setMap(
          rerac.protos.InstanceCollection.FeatureMap.Builder builderForValue) {
        if (mapBuilder_ == null) {
          map_ = builderForValue.build();
          onChanged();
        } else {
          mapBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeMap(rerac.protos.InstanceCollection.FeatureMap value) {
        if (mapBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              map_ != rerac.protos.InstanceCollection.FeatureMap.getDefaultInstance()) {
            map_ =
              rerac.protos.InstanceCollection.FeatureMap.newBuilder(map_).mergeFrom(value).buildPartial();
          } else {
            map_ = value;
          }
          onChanged();
        } else {
          mapBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearMap() {
        if (mapBuilder_ == null) {
          map_ = rerac.protos.InstanceCollection.FeatureMap.getDefaultInstance();
          onChanged();
        } else {
          mapBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public rerac.protos.InstanceCollection.FeatureMap.Builder getMapBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMapFieldBuilder().getBuilder();
      }
      public rerac.protos.InstanceCollection.FeatureMapOrBuilder getMapOrBuilder() {
        if (mapBuilder_ != null) {
          return mapBuilder_.getMessageOrBuilder();
        } else {
          return map_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          rerac.protos.InstanceCollection.FeatureMap, rerac.protos.InstanceCollection.FeatureMap.Builder, rerac.protos.InstanceCollection.FeatureMapOrBuilder> 
          getMapFieldBuilder() {
        if (mapBuilder_ == null) {
          mapBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              rerac.protos.InstanceCollection.FeatureMap, rerac.protos.InstanceCollection.FeatureMap.Builder, rerac.protos.InstanceCollection.FeatureMapOrBuilder>(
                  map_,
                  getParentForChildren(),
                  isClean());
          map_ = null;
        }
        return mapBuilder_;
      }
      
      // repeated .rerac.protos.Instance instance = 2;
      private java.util.List<rerac.protos.InstanceCollection.Instance> instance_ =
        java.util.Collections.emptyList();
      private void ensureInstanceIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          instance_ = new java.util.ArrayList<rerac.protos.InstanceCollection.Instance>(instance_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          rerac.protos.InstanceCollection.Instance, rerac.protos.InstanceCollection.Instance.Builder, rerac.protos.InstanceCollection.InstanceOrBuilder> instanceBuilder_;
      
      public java.util.List<rerac.protos.InstanceCollection.Instance> getInstanceList() {
        if (instanceBuilder_ == null) {
          return java.util.Collections.unmodifiableList(instance_);
        } else {
          return instanceBuilder_.getMessageList();
        }
      }
      public int getInstanceCount() {
        if (instanceBuilder_ == null) {
          return instance_.size();
        } else {
          return instanceBuilder_.getCount();
        }
      }
      public rerac.protos.InstanceCollection.Instance getInstance(int index) {
        if (instanceBuilder_ == null) {
          return instance_.get(index);
        } else {
          return instanceBuilder_.getMessage(index);
        }
      }
      public Builder setInstance(
          int index, rerac.protos.InstanceCollection.Instance value) {
        if (instanceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstanceIsMutable();
          instance_.set(index, value);
          onChanged();
        } else {
          instanceBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setInstance(
          int index, rerac.protos.InstanceCollection.Instance.Builder builderForValue) {
        if (instanceBuilder_ == null) {
          ensureInstanceIsMutable();
          instance_.set(index, builderForValue.build());
          onChanged();
        } else {
          instanceBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addInstance(rerac.protos.InstanceCollection.Instance value) {
        if (instanceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstanceIsMutable();
          instance_.add(value);
          onChanged();
        } else {
          instanceBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addInstance(
          int index, rerac.protos.InstanceCollection.Instance value) {
        if (instanceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstanceIsMutable();
          instance_.add(index, value);
          onChanged();
        } else {
          instanceBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addInstance(
          rerac.protos.InstanceCollection.Instance.Builder builderForValue) {
        if (instanceBuilder_ == null) {
          ensureInstanceIsMutable();
          instance_.add(builderForValue.build());
          onChanged();
        } else {
          instanceBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addInstance(
          int index, rerac.protos.InstanceCollection.Instance.Builder builderForValue) {
        if (instanceBuilder_ == null) {
          ensureInstanceIsMutable();
          instance_.add(index, builderForValue.build());
          onChanged();
        } else {
          instanceBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllInstance(
          java.lang.Iterable<? extends rerac.protos.InstanceCollection.Instance> values) {
        if (instanceBuilder_ == null) {
          ensureInstanceIsMutable();
          super.addAll(values, instance_);
          onChanged();
        } else {
          instanceBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearInstance() {
        if (instanceBuilder_ == null) {
          instance_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          instanceBuilder_.clear();
        }
        return this;
      }
      public Builder removeInstance(int index) {
        if (instanceBuilder_ == null) {
          ensureInstanceIsMutable();
          instance_.remove(index);
          onChanged();
        } else {
          instanceBuilder_.remove(index);
        }
        return this;
      }
      public rerac.protos.InstanceCollection.Instance.Builder getInstanceBuilder(
          int index) {
        return getInstanceFieldBuilder().getBuilder(index);
      }
      public rerac.protos.InstanceCollection.InstanceOrBuilder getInstanceOrBuilder(
          int index) {
        if (instanceBuilder_ == null) {
          return instance_.get(index);  } else {
          return instanceBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends rerac.protos.InstanceCollection.InstanceOrBuilder> 
           getInstanceOrBuilderList() {
        if (instanceBuilder_ != null) {
          return instanceBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(instance_);
        }
      }
      public rerac.protos.InstanceCollection.Instance.Builder addInstanceBuilder() {
        return getInstanceFieldBuilder().addBuilder(
            rerac.protos.InstanceCollection.Instance.getDefaultInstance());
      }
      public rerac.protos.InstanceCollection.Instance.Builder addInstanceBuilder(
          int index) {
        return getInstanceFieldBuilder().addBuilder(
            index, rerac.protos.InstanceCollection.Instance.getDefaultInstance());
      }
      public java.util.List<rerac.protos.InstanceCollection.Instance.Builder> 
           getInstanceBuilderList() {
        return getInstanceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rerac.protos.InstanceCollection.Instance, rerac.protos.InstanceCollection.Instance.Builder, rerac.protos.InstanceCollection.InstanceOrBuilder> 
          getInstanceFieldBuilder() {
        if (instanceBuilder_ == null) {
          instanceBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rerac.protos.InstanceCollection.Instance, rerac.protos.InstanceCollection.Instance.Builder, rerac.protos.InstanceCollection.InstanceOrBuilder>(
                  instance_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          instance_ = null;
        }
        return instanceBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:rerac.protos.InstanceCollectionPB)
    }
    
    static {
      defaultInstance = new InstanceCollectionPB(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rerac.protos.InstanceCollectionPB)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rerac_protos_FeatureMap_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rerac_protos_FeatureMap_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rerac_protos_Instance_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rerac_protos_Instance_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rerac_protos_Instance_Feature_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rerac_protos_Instance_Feature_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rerac_protos_InstanceCollectionPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rerac_protos_InstanceCollectionPB_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&rerac/protos/instance_collection.proto" +
      "\022\014rerac.protos\"D\n\nFeatureMap\022\017\n\007feature\030" +
      "\001 \003(\t\022\023\n\013featureHash\030\002 \003(\005\022\020\n\010category\030\003" +
      " \003(\t\"\251\001\n\010Instance\022/\n\007feature\030\001 \003(\0132\036.rer" +
      "ac.protos.Instance.Feature\022\031\n\016category_i" +
      "ndex\030\002 \001(\005:\0010\022\020\n\010category\030\003 \001(\t\022\026\n\010posit" +
      "ive\030\004 \001(\010:\004true\032\'\n\007Feature\022\r\n\005index\030\001 \002(" +
      "\005\022\r\n\005value\030\002 \002(\001\"g\n\024InstanceCollectionPB" +
      "\022%\n\003map\030\001 \002(\0132\030.rerac.protos.FeatureMap\022" +
      "(\n\010instance\030\002 \003(\0132\026.rerac.protos.Instanc",
      "e"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rerac_protos_FeatureMap_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rerac_protos_FeatureMap_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rerac_protos_FeatureMap_descriptor,
              new java.lang.String[] { "Feature", "FeatureHash", "Category", },
              rerac.protos.InstanceCollection.FeatureMap.class,
              rerac.protos.InstanceCollection.FeatureMap.Builder.class);
          internal_static_rerac_protos_Instance_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rerac_protos_Instance_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rerac_protos_Instance_descriptor,
              new java.lang.String[] { "Feature", "CategoryIndex", "Category", "Positive", },
              rerac.protos.InstanceCollection.Instance.class,
              rerac.protos.InstanceCollection.Instance.Builder.class);
          internal_static_rerac_protos_Instance_Feature_descriptor =
            internal_static_rerac_protos_Instance_descriptor.getNestedTypes().get(0);
          internal_static_rerac_protos_Instance_Feature_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rerac_protos_Instance_Feature_descriptor,
              new java.lang.String[] { "Index", "Value", },
              rerac.protos.InstanceCollection.Instance.Feature.class,
              rerac.protos.InstanceCollection.Instance.Feature.Builder.class);
          internal_static_rerac_protos_InstanceCollectionPB_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_rerac_protos_InstanceCollectionPB_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rerac_protos_InstanceCollectionPB_descriptor,
              new java.lang.String[] { "Map", "Instance", },
              rerac.protos.InstanceCollection.InstanceCollectionPB.class,
              rerac.protos.InstanceCollection.InstanceCollectionPB.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
